### ISSUE TITLE
WEPopoverController show view and after second closed it

### ISSUE THREAD

**Issue by alisichkin** [werner77/WEPopover#65]
I try to show view using popover. Since UIPopoverController does not work on IPhone i use WEPopoverController.

My code:
```
UIViewController *controller = [[UIStoryboard storyboardWithName:@"Main" bundle:nil]instantiateViewControllerWithIdentifier:@"GetDateController"];
controller.modalPresentationStyle = UIModalPresentationPopover;
WEPopoverController *pop = [[WEPopoverController alloc] initWithContentViewController:controller];
pop.delegate = self;
CGRect screen = [[UIScreen mainScreen]bounds];
CGRect r = CGRectMake(8, 8, screen.size.width-8, 57);
pop.popoverContentSize = r.size;
[pop presentPopoverFromRect:CGRectMake(200, 100, 0, 0) inView:self.view permittedArrowDirections:UIPopoverArrowDirectionAny animated:YES];
```
When I start the program, I see a pop over window, which immediately disappears. When I use UIPopoverController on IPhone program crash, on iPad everything works correctly.

What do I need to do with WEPopoverController to make it work?

Alexander.

**Comment by werner77** [comment]
Hi,

You need to retain the WEPopoverController instance (i.e. assign it to a strong instance variable or property).

Regards, Werner
