### ISSUE TITLE
ModalViewController

### ISSUE THREAD

**Issue by robderijk** [werner77/WEPopover#8]
When there is a modalviewcontroller in the foreground and the popover is triggered inside the modalviewcontroller it shows itself behind the modalviewcontroller.

**Comment by danwebservice** [comment]
@jonklein It works for me too.

**Comment by werner77** [comment]
The parent view for the popover can be set manually using the parentView property of WEPopoverController. On newer iOS versions (>= 8.0) it makes sense to make the parentView the active window, since auto rotation works for direct subviews of UIWindow now.
